clockwork/urls.py
from django.conf.urls import url

from . import views

app_name = 'clockwork'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alljobsview/', views.AllJobsView.as_view(), name='alljobsview'),
    url(r'^jobshortlistview/', views.JobShortlistView.as_view(), name='jobshortlistview'),
    url(r'^iamajobseeker/', views.IamajobseekerView.as_view(), name='iamajobseeker'),
    url(r'^postajob/', views.PostajobView.as_view(), name='postajob'),
    url(r'^iamanemployer/', views.IamanemployerView.as_view(), name='iamanemployer'),
    #url(r'^employerseemyjob/', views.EmployerSeeMyJob.as_view(), name='employerseemyjob'),
    url(r'^(?P<pk>[0-9]+)/employerseemyjob/$', views.EmployerSeeMyJob.as_view(), name='employerseemyjob'),
    url(r'^(?P<pk>[0-9]+)/jobseekerjobview/$', views.JobseekerJobView.as_view(), name='jobseekerjobview'),
    url(r'^(?P<pk>[0-9]+)/jobseekerprofileview/$', views.JobseekerProfileView.as_view(), name='jobseekerprofileview'),
    url(r'^(?P<pk>[0-9]+)/jobseekerapplied/$', views.JobseekerApplied.as_view(), name='jobseekerapplied'),
]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^clockwork/', include('clockwork.urls')),
    url(r'^admin/', admin.site.urls),
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^clockwork/', include('clockwork.urls')),
    url(r'^admin/', admin.site.urls),
]

clockwork/models.py
from django.db import models
from django.forms import ModelForm
from datetime import datetime
from django.core.urlresolvers import reverse

INDUSTRY_CHOICES = (
    ('Construction','Construction'),
    ('Promotions','Promotions'),
    ('Events', 'Events'),
    ('Barwork', 'Barwork'),
    ('Gardener', 'Gardening'),
    ('Cleaning', 'Cleaning'),
    ('Transport', 'Transport'),
    )

class Employer(models.Model):
    name = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone_no = models.CharField(max_length=12)

    def __str__(self):
        return self.name

class Jobseeker (models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone_number = models.CharField(max_length=12) 
    home_location = models.CharField(max_length=150)
    industry = models.CharField(max_length=12, choices=INDUSTRY_CHOICES)
    other_industry = models.CharField(max_length=150)
    id_number = models.CharField(primary_key=True, max_length=13)
    

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('clockwork:jobseekerprofileview', kwargs={'pk':self.pk})


class Job(models.Model):
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.now)
    time = models.TimeField(default=datetime.now)
    job_location = models.CharField(max_length=150)
    job_description = models.CharField(max_length=180)
    job_title = models.CharField(max_length=20)
    wage = models.CharField(max_length=6, default=0)
    jobs = models.ManyToManyField(Jobseeker)

    def __str__(self):              # __unicode__ on Python 2
        return self.job_title
        self.employer_id

    def get_absolute_url(self):
        return reverse('clockwork:employerseemyjob', kwargs={'pk':self.pk})


##class Shortlist (models.Model):
##
##    jobseeker_id = models.ForeignKey(Jobseeker, on_delete=models.CASCADE) #reference jobseeker model
##    job_id = models.ForeignKey(job_id, on_delete=models.CASCADE) #reference job model
    

clockwork/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Job, Jobseeker, Employer
from django.views.generic.edit import CreateView, UpdateView, DeleteView

def index(request):
    return render(request, "clockwork/index.html",{})

class AllJobsView(generic.ListView):
    template_name = 'clockwork/alljobsview.html'
    context_object_name = 'latest_job_list'

    def get_queryset(self):
        """Return the last five published jobs."""
        return Job.objects.order_by('date')[:100]



class IamajobseekerView(CreateView):
    model = Jobseeker
    fields = ['name', 'email', 'phone_number', 'home_location', 'industry', 'other_industry', 'id_number']
    #template_name = 'jobseekertemplate.html'


class PostajobView(CreateView):
    model = Job
    fields = ['employer', 'job_location', 'job_description', 'job_title', 'wage', 'date', 'time']

class IamanemployerView(CreateView):
    model = Employer
    fields = ['name', 'company', 'email', 'phone_no']
    #template_name = 'employertemplate.html'

class EmployerSeeMyJob(generic.DetailView):
    model = Job
    template_name = 'clockwork/employerseemyjob.html'

    def get_context_data(self, **kwargs):
        context=super(EmployerSeeMyJob, self).get_context_data(**kwargs)
        #job_pk = Job.objects.get(pk=self.kwargs.get('pk')) #Get this job's pk
        job_pk = self.kwargs['pk']
        context['jobseeker_list']=Job.objects.filter(pk=job_pk)[0].jobs.all()
        return context

class JobseekerJobView (generic.DetailView):
    model = Job
    template_name = 'clockwork/jobseekerjobview.html'

    

class JobseekerProfileView (generic.DetailView):
    model = Jobseeker
    template_name = 'clockwork/jobseekerprofileview.html'

class JobShortlistView(generic.ListView):
    template_name = 'clockwork/jobshortlistview.html'
    context_object_name = 'latest_job_shortlist'

    def get_queryset(self):
        """Return the last hundred published jobseekers."""
        return Jobseeker.objects.order_by('date')[:100]
    
class JobseekerApplied (generic.DetailView):
    model = Job
    template_name = 'clockwork/jobseekerapplied.html'

##def postjob(request, job_id):
##    return HttpResponse("Thanks for posting a job. Your job reference number is %s" % job_id)
##    job = get_object_or_404(Job, pk=pk)
##    try:
##        selected_employer = job.choice_set.get(pk=request.POST['employer'])
##    except (KeyError, Choice.DoesNotExist):
##        # Redisplay the question voting form.
##        return render(request, 'clockwork/detail.html',{'job': job,'error_message': "You didn't post a job.",})
##    
##    else:
##        selected_job.postjob += 1
##        selected_job.save()
##        # Always return an HttpResponseRedirect after successfully dealing
##        # with POST data. This prevents data from being posted twice if a
##        # user hits the Back button.
##        return HttpResponseRedirect(reverse('clockwork:postajob', args=(job.id)))

clockwork/templates/clockwork/alljobsview.html
{% load staticfiles %}

<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<div id="banner">
<h1>Clockwork<h1>
<p></p>
<h3>Search jobs below</h3>
<h4 align="left">Click to see more info and apply<align></h4>
<br><br><br>
<br><br><br>
</div>
<h5>Jobs<h5>

<body>

{% if latest_job_list %}
    <ul>
    {% for job in latest_job_list %}
        <li><a href="{% url 'clockwork:jobseekerjobview' job.id %}">{{ job.job_title}} @ {{job.job_location}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No jobs are available.</p>
{% endif %}
</body>
<h3>Not registered yet?</h3>
<input type="button" onclick="location.href = 'http://127.0.0.1:8000/clockwork/iamanemployer'" value="Employer" />
<input type="button" onclick="location.href = 'http://127.0.0.1:8000/clockwork/iamajobseeker'" value="Jobseeker" />

clockwork/templates/clockwork/employer_form.html
{% load staticfiles %}
<h1>Clockwork Employer</h1>
<h2>Enter your details</h2>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="button" onclick="location.href = 'http://127.0.0.1:8000/clockwork/postajob/'" value="Submit" />
</form>
<a href=http://127.0.0.1:8000/clockwork/alljobsview>Back to home<a/>

clockwork/templates/clockwork/employerseemyjob.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<h1>{{ object.job_title }}</h1>
<hr>
<p>Date: {{ object.date }}</p>
<p>Time: {{ object.time }}</p>
<p>Job Title: {{ object.job_title }}</p>
<p>Job Location: {{ object.job_location }}</p>
<p>Job Description: {{ object.job_description }}</p>
<p>Wage: {{ object.wage }}</p>
<hr>
{% if jobseeker_list %}
    <ul>
    {% for jobseeker in jobseeker_list %}
        <li><a href="{% url 'clockwork:jobseekerprofileview' jobseeker.id_number %}">{{ jobseeker.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No jobseekers have applied yet.</p>
{% endif %}
<a href=http://127.0.0.1:8000/clockwork/postajob/>Post another job</a>

clockwork/templates/clockwork/index.html
{%load staticfiles%}
<head>


<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" />
</head>
<div id="banner">
	<h1>Clockwork</h1>
	<div style="position:fixed; bottom: 10%; width: 100%;">
		<a href="http://127.0.0.1:8000/clockwork/iamajobseeker/" class="button">Jobseeker</a>
		<a href="http://127.0.0.1:8000/clockwork/iamanemployer/" class="button">Employer</a>
	</div>
</div>

<p>Clockwork write up</p>

</html>

clockwork/templates/clockwork/job_form.html
{% load staticfiles %}
<h1>Post a Job</h1>
<h3>Enter job details below:</h3>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Post a job" />
</form>

clockwork/templates/clockwork/jobseeker_form.html
{% load staticfiles %}
<h1>Clockwork Jobseeker</h1>
<h3>Enter your details below:</h3>
<a href=http://127.0.0.1:8000/clockwork/alljobsview/ class="button">Already registered? </a>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

clockwork/templates/clockwork/jobseekerapplied.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<div id=banner2>
<h1>{{ object.job_title }}</h1>
<hr>
</div>

<p>Date: {{ object.date }}</p>
<p>Time: {{ object.time }}</p>
<p>Job Title: {{ object.job_title }}</p>
<p>Job Location: {{ object.job_location }}</p>
<p>Job Description: {{ object.job_description }}</p>
<p>Wage: {{ object.wage }}</p>
<h4><font color="black">Thanks for applying to be a {{ object.job_title }}. You will hear back shortly.</font></h4>
<a href=http://127.0.0.1:8000/clockwork/alljobsview/>Back to all jobs</a>

clockwork/templates/clockwork/jobseekerjobview.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<div id=banner2>
<h1>{{ object.job_title }}</h1>
<br>
</div>

<p>Date: {{ object.date }}</p>
<p>Time: {{ object.time }}</p>
<p>Job Title: {{ object.job_title }}</p>
<p>Job Location: {{ object.job_location }}</p>
<p>Job Description: {{ object.job_description }}</p>
<p>Wage: {{ object.wage }}</p>
<input type="button" onclick="location.href = '{% url 'clockwork:jobseekerapplied' job.id %}'" value="Apply" />
<br><br>
<a href=http://127.0.0.1:8000/clockwork/alljobsview/>Back to all jobs</a>

clockwork/templates/clockwork/jobseekerprofileview.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<h1>{{ object.name }}</h1>
<hr>
<p>Email: {{ object.email }}</p>
<p>Phone Number: {{ object.phone_number }}</p>
<p>Hometown: {{ object.home_location }}</p>
<p>You are interested in: {{ object.industry }}, and {{ object.other_industry }}</p>
<p>ID Number: {{ object.id_number }}</p>
<input type="button" onclick="location.href = 'http://127.0.0.1:8000/clockwork/alljobsview/'" value="Find a Job" />
<hr>

clockwork/templates/clockwork/jobshortlistview.html
{% if latest_job_shortlist %}
    <ul>
    {% for jobseeker in latest_job_shortlist %}
        <li><a href="{% url 'clockwork:jobseekerjobview' jobseeker.id %}"> contact {{ jobseeker.name}}, on {{job.phone_number}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No jobseekers have applied yet.</p>
{% endif %}

clockwork/templates/clockwork/postajobtemplate.html
{% load staticfiles %}
<h1>Post a Job</h1>
<h3>Enter job details below:</h3>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Post Job" />
</form>